/**
 * Integration tests for extern import auto-binding from JVM class metadata.
 *
 * Tests that extern import declarations are:
 * 1. Expanded into ExternTypeDecl + ExternFunDecl nodes before typecheck
 * 2. Usable as normal extern declarations in Kestrel code
 * 3. Emits .extern.ks sidecar files alongside .class output
 */
import { describe, it, expect } from 'vitest';
import { mkdirSync, writeFileSync, rmSync, existsSync, readFileSync } from 'fs';
import { join } from 'path';
import { fileURLToPath } from 'node:url';
import { compileFileJvm } from '../../src/compile-file-jvm.js';
import { parse } from '../../src/parser/index.js';
import { tokenize } from '../../src/lexer/index.js';

const compilerRoot = fileURLToPath(new URL('../..', import.meta.url));
const kestrelRoot = join(compilerRoot, '..');
const stdlibDir = join(kestrelRoot, 'stdlib');

describe('extern import: parsing', () => {
  it('parses extern import declaration as ExternImportDecl', () => {
    const ast = parse(tokenize('extern import "java:java.util.HashMap" as HashMap { }'));
    expect(ast.kind).toBe('Program');
    const decl = ast.body[0];
    expect(decl).toMatchObject({
      kind: 'ExternImportDecl',
      target: 'java:java.util.HashMap',
      alias: 'HashMap',
    });
  });

  it('parses extern import with override block', () => {
    const ast = parse(tokenize(
      'extern import "java:java.util.HashMap" as HashMap { fun size(m: HashMap): Int }'
    ));
    const decl = ast.body[0];
    if (decl.kind === 'ExternImportDecl') {
      expect(decl.overrides.length).toBe(1);
      expect(decl.overrides[0].name).toBe('size');
    } else {
      expect.fail('Expected ExternImportDecl');
    }
  });
});

describe('extern import: compilation against JDK class', () => {
  it('compiles a module that uses extern import for java.util.HashMap', () => {
    const tmpDir = join(compilerRoot, 'test', 'integration', '_tmp_extern_import_hashmap');
    mkdirSync(tmpDir, { recursive: true });
    const srcPath = join(tmpDir, 'TestHashMap.ks');

    writeFileSync(srcPath, `
extern import "java:java.util.HashMap" as HashMap { }

fun main(): Unit = {
  val m = newHashMap()
  put(m, "x", "y")
  println("done")
}
`);
    try {
      const result = compileFileJvm(srcPath, {
        projectRoot: kestrelRoot,
        stdlibDir,
        getClassOutputDir: () => tmpDir,
      });
      if (!result.ok) {
        console.error('Compile errors:', result.diagnostics.map((d) => d.message).join('\n'));
      }
      expect(result.ok).toBe(true);
    } finally {
      rmSync(tmpDir, { recursive: true, force: true });
    }
  });

  it('compiles a module using extern import with method type override', () => {
    const tmpDir = join(compilerRoot, 'test', 'integration', '_tmp_extern_import_override');
    mkdirSync(tmpDir, { recursive: true });
    const srcPath = join(tmpDir, 'TestOverride.ks');

    // Override the size() return type to be exactly Int (same as auto-generated)
    writeFileSync(srcPath, `
extern import "java:java.util.HashMap" as HashMap {
  fun size(instance: HashMap): Int
}

fun getSize(): Int = {
  val m = newHashMap()
  size(m)
}

fun main(): Unit = println(getSize())
`);
    try {
      const result = compileFileJvm(srcPath, {
        projectRoot: kestrelRoot,
        stdlibDir,
        getClassOutputDir: () => tmpDir,
      });
      if (!result.ok) {
        console.error('Compile errors:', result.diagnostics.map((d) => d.message).join('\n'));
      }
      expect(result.ok).toBe(true);
    } finally {
      rmSync(tmpDir, { recursive: true, force: true });
    }
  });
});

describe('extern import: sidecar .extern.ks emission', () => {
  it('emits <Alias>.extern.ks alongside the compiled .class file', () => {
    const tmpDir = join(compilerRoot, 'test', 'integration', '_tmp_extern_import_sidecar');
    mkdirSync(tmpDir, { recursive: true });
    const srcPath = join(tmpDir, 'TestSidecar.ks');

    writeFileSync(srcPath, `
extern import "java:java.util.HashMap" as HashMap { }

fun main(): Unit = println("sidecar test")
`);
    try {
      const result = compileFileJvm(srcPath, {
        projectRoot: kestrelRoot,
        stdlibDir,
        getClassOutputDir: () => tmpDir,
      });
      expect(result.ok).toBe(true);

      // Sidecar file should exist
      const sidecarPath = join(tmpDir, 'HashMap.extern.ks');
      expect(existsSync(sidecarPath)).toBe(true);

      const sidecarContent = readFileSync(sidecarPath, 'utf-8');
      // Must contain the auto-generated comment
      expect(sidecarContent).toContain('Auto-generated by Kestrel compiler from java.util.HashMap');
      // Must contain the extern type declaration
      expect(sidecarContent).toContain('extern type HashMap = jvm("java.util.HashMap")');
      // Must contain extern fun stubs
      expect(sidecarContent).toContain('extern fun size(instance: HashMap): Int');
      expect(sidecarContent).toContain('extern fun newHashMap()');
    } finally {
      rmSync(tmpDir, { recursive: true, force: true });
    }
  });

  it('sidecar content is valid Kestrel extern syntax', () => {
    const tmpDir = join(compilerRoot, 'test', 'integration', '_tmp_extern_import_sidecar2');
    mkdirSync(tmpDir, { recursive: true });
    const srcPath = join(tmpDir, 'TestSidecar2.ks');

    writeFileSync(srcPath, `
extern import "java:java.util.HashMap" as HashMap { }
fun main(): Unit = println("ok")
`);
    try {
      const result = compileFileJvm(srcPath, {
        projectRoot: kestrelRoot,
        stdlibDir,
        getClassOutputDir: () => tmpDir,
      });
      expect(result.ok).toBe(true);

      const sidecarPath = join(tmpDir, 'HashMap.extern.ks');
      expect(existsSync(sidecarPath)).toBe(true);
      const content = readFileSync(sidecarPath, 'utf-8');

      // Each extern fun line should follow the pattern: extern fun name(params): ReturnType = jvm("...")
      const externFunLines = content.split('\n').filter((l) => l.startsWith('extern fun'));
      expect(externFunLines.length).toBeGreaterThan(0);
      for (const line of externFunLines) {
        // Allow optional ':ReturnType' suffix inside the jvm("...") string for primitive-returning methods
        expect(line).toMatch(/^extern fun \w+\(.*\): [\w<>,\s]+ = jvm\(".*"\)$/);
      }
    } finally {
      rmSync(tmpDir, { recursive: true, force: true });
    }
  });
});

describe('extern import: unsupported scheme error', () => {
  it('reports an error for unsupported scheme', () => {
    const tmpDir = join(compilerRoot, 'test', 'integration', '_tmp_extern_import_err');
    mkdirSync(tmpDir, { recursive: true });
    const srcPath = join(tmpDir, 'TestErr.ks');

    writeFileSync(srcPath, `extern import "http:java.util.HashMap" as HashMap { }\nfun main(): Unit = println("x")\n`);
    try {
      const result = compileFileJvm(srcPath, {
        projectRoot: kestrelRoot,
        stdlibDir,
        getClassOutputDir: () => tmpDir,
      });
      expect(result.ok).toBe(false);
      if (!result.ok) {
        expect(result.diagnostics.some((d) => d.message.includes('unsupported scheme'))).toBe(true);
      }
    } finally {
      rmSync(tmpDir, { recursive: true, force: true });
    }
  });

  it('reports an error for unknown class name', () => {
    const tmpDir = join(compilerRoot, 'test', 'integration', '_tmp_extern_import_err2');
    mkdirSync(tmpDir, { recursive: true });
    const srcPath = join(tmpDir, 'TestErr2.ks');

    writeFileSync(srcPath, `extern import "java:com.example.NonExistent" as NE { }\nfun main(): Unit = println("x")\n`);
    try {
      const result = compileFileJvm(srcPath, {
        projectRoot: kestrelRoot,
        stdlibDir,
        getClassOutputDir: () => tmpDir,
      });
      expect(result.ok).toBe(false);
      if (!result.ok) {
        expect(result.diagnostics.some((d) => d.message.includes('extern import'))).toBe(true);
      }
    } finally {
      rmSync(tmpDir, { recursive: true, force: true });
    }
  });
});

describe('extern import: sidecar reflects user overrides', () => {
  it('sidecar shows overridden signature for overridden method and auto-generated for others', () => {
    const tmpDir = join(compilerRoot, 'test', 'integration', '_tmp_extern_import_override_sidecar');
    mkdirSync(tmpDir, { recursive: true });
    const srcPath = join(tmpDir, 'TestOverrideSidecar.ks');

    // Override 'append' to use a concrete SB type instead of auto-generated _T0
    writeFileSync(srcPath, `
extern import "java:java.lang.StringBuilder" as SB {
  fun append(instance: SB, p0: String): SB
}
fun main(): Unit = println("override sidecar test")
`);
    try {
      const result = compileFileJvm(srcPath, {
        projectRoot: kestrelRoot,
        stdlibDir,
        getClassOutputDir: () => tmpDir,
      });
      if (!result.ok) {
        console.error('Compile errors:', result.diagnostics.map((d) => d.message).join('\n'));
      }
      expect(result.ok).toBe(true);

      const sidecarPath = join(tmpDir, 'SB.extern.ks');
      expect(existsSync(sidecarPath)).toBe(true);
      const content = readFileSync(sidecarPath, 'utf-8');

      // The overridden 'append' should show the user-provided signature
      expect(content).toContain('extern fun append(instance: SB, p0: String): SB');
      // The non-overridden 'toString' should still be auto-generated (returns String)
      expect(content).toContain('extern fun toString(instance: SB): String');
    } finally {
      rmSync(tmpDir, { recursive: true, force: true });
    }
  });
});
